# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,]
neo_version=21.1.218
loader_version_range=[1,)

## Mod Properties
mod_id=enderfuge
mod_build=enderfuge-neo
mod_name=Enderfuge
mod_license=https://github.com/MasterGeneral156/Enderfuge/blob/1.21/LICENSE
mod_version=1.21.1-1.0.0
mod_group_id=themastergeneral.enderfuge
ctd_core_ver=1.21.1-2.7.1b
